### ISSUE TITLE
处理 const csrfMatch = COOKIE_STRING.match(/bili_jct=(.*?);/); 出错

### ISSUE THREAD

**Issue by Yang-qwq** [MoyuScript/bilibili-delete-all-dynamic#2]
`ps: 刚学node.js没多久，纯萌新`
填入.env后启动，程序报错
```env
// 这三行我都试了一遍，均报错
COOKIE_STRING="buvid3=23F28710-****-149A1EB34A1731237infoc; ...... ; innersign=0; CURRENT_FNVAL=80"
COOKIE_STRING="cookie: buvid3=23F28710-****-149A1EB34A1731237infoc; ...... ; innersign=0; CURRENT_FNVAL=80"
COOKIE_STRING="bili_jct=fb06e***" // 只填bili_jct
```
输出：
```
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'match')
    at <anonymous> (c:\Users\Yang\source\repos\bilibili-delete-all-dynamic\index.js:8:33)
    at run (node:internal/modules/esm/module_job:197:25)
    --- async function ---
    at runMainESM (node:internal/modules/run_main:51:21)
    at executeUserEntryPoint (node:internal/modules/run_main:74:5)
    at <anonymous> (node:internal/main/run_main_module:17:47)
Process exited with code 1

```
试着改了一下源码：
```javascript
// console.log(process.env)

// console.log(COOKIE_STRING);

// const csrfMatch = COOKIE_STRING.match(/bili_jct=(.*?);/);
const csrfMatch = '***' // 直接填入bili_jct的值

// if (!csrfMatch) {
//     throw new Error('Cookie 缺少 bili_jct');
// }

// const csrf = csrfMatch[1];
const csrf = csrfMatch;

const headers = {
    'cookie': '***' // 直接填入cookie
}

async function getSelfUid() {
    const req = got('https://api.bilibili.com/x/web-interface/nav', {
        headers
    });
    const resp = await req.json();

    return resp.data.mid;
}

...
```
改完之后代码工作的很好
而且我注意到代码里似乎没有`package-lock.json` 请问一下有可能是依赖版本的问题吗？

**Comment by MoyuScript** [comment]
你这是环境变量没加载上，正常情况下 `.env` 中的环境变量会被加载进来，检查一下依赖是否安装好，还有 .env 文件是否配置正确

**Comment by Yang-qwq** [comment]
已经检查过了，仍然还是报错
```
PS C:\Users\Yang\source\repos\bilibili-delete-all-dynamic> npm install

up to date, audited 38 packages in 3s

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\Yang\source\repos\bilibili-delete-all-dynamic> npm run start

> start
> node index.js

file:///C:/Users/Yang/source/repos/bilibili-delete-all-dynamic/index.js:8
const csrfMatch = COOKIE_STRING.match(/bili_jct=(.*?);/);
                                ^

TypeError: Cannot read properties of undefined (reading 'match')
    at file:///C:/Users/Yang/source/repos/bilibili-delete-all-dynamic/index.js:8:33
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
PS C:\Users\Yang\source\repos\bilibili-delete-all-dynamic> notepad .\.env
PS C:\Users\Yang\source\repos\bilibili-delete-all-dynamic>
```

**Comment by MoyuScript** [comment]
Node 版本，.env 文件内容和目录结构发一下看看

**Comment by Yang-qwq** [comment]
node版本：v16.14.2
npm版本：8.5.0
.env内容可以参考之前试过的第一行
目录结构：
```
PS C:\Users\Yang\source\repos\bilibili-delete-all-dynamic> tree /F .
文件夹 PATH 列表
卷序列号为 00000019 8AC2:3778
C:\USERS\YANG\SOURCE\REPOS\BILIBILI-DELETE-ALL-DYNAMIC
│  .env
│  .env.example
│  .gitignore
│  index.js
│  package-lock.json
│  package.json
│  pnpm-lock.yaml
│  README.md
│
├─.vscode
│      launch.json
│
└─node_modules
    │  .package-lock.json
 ...

PS C:\Users\Yang\source\repos\bilibili-delete-all-dynamic>
```

**Comment by MoyuScript** [comment]
你试试把 config() 那行打印出来看看，我这边之后也看看能不能复现。

**Comment by Yang-qwq** [comment]
打印出来的结果：
```
C:\Program Files\nodejs\npm.cmd run-script start

> start
> node index.js
{parsed: {…}}
parsed: {}
[[Prototype]]: Object
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
__proto__: ƒ __proto__()
constructor: ƒ Object()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ toString()
valueOf: ƒ valueOf()
[[Prototype]]: Object
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
__proto__: ƒ __proto__()
constructor: ƒ Object()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ toString()
valueOf: ƒ valueOf()
Process exited with code 1

```

**Comment by Yang-qwq** [comment]
就是一个空的json
```javascript
{}
```

**Comment by MoyuScript** [comment]
说明环境变量没加载出来，是不是权限有问题？

你可以试试 https://www.npmjs.com/package/dotenv 的例子，看看能否正常工作。

**Comment by Yang-qwq** [comment]
例子工作的很好
```json
{
  ALLUSERSPROFILE: 'C:\\ProgramData',
  APPDATA: 'C:\\Users\\Yang\\AppData\\Roaming',
  CommonProgramFiles: 'C:\\Program Files\\Common Files',
  'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
  CommonProgramW6432: 'C:\\Program Files\\Common Files',
...
  USERNAME: 'Yang',
  USERPROFILE: 'C:\\Users\\Yang',
  windir: 'C:\\Windows'
}
```

**Comment by Yang-qwq** [comment]
是的，它加载出来了
```env
S3_BUCKET="YOURS3BUCKET"
SECRET_KEY="YOURSECRETKEYGOESHERE"
ME="Yang"
```
```js
{
  ME: 'Yang',
  S3_BUCKET: 'YOURS3BUCKET',
  SECRET_KEY: 'YOURSECRETKEYGOESHERE'
}
```

**Comment by Yang-qwq** [comment]
刚刚在我的linux服务器上测试了一下，没有任何的问题
可能这个问题只是特例？

**Comment by MoyuScript** [comment]
看看是不是文件权限有问题

**Comment by Yang-qwq** [comment]
权限也没有任何问题
这个问题应该只是特例吧
